### PR TITLE
Major cleanup before integration in CloudCompare

### PR DESCRIPTION
**Pull request by dgirardeau**

### CODE REVIEW

**Comment by dgirardeau** [comment]
@truebelief I made a big cleanup, that may be a little bit hard to review ;)

Can you test it on your side?

And do you have some sample files for us to test by the way?

**Comment by truebelief** [comment]
This is quite a lot of cleanup, thanks a lot! I am running and testing it now with different datasets. If this works on my end, I will send data and files for your further testing.

**Comment by truebelief** [comment]
Here's one of our reference tree plot scans: https://drive.google.com/file/d/1Kv7uGIEqKXTSWG6T91hMpDE5luTHhJZs/view?usp=share_link. It's been manually segregated into distinct scalar fields for tree stems, individual trees, and ground classes. Given its natural complexity, I believe it's a robust file for testing. The treeiso function can be tested on a subset of the dataset excluding the ground, while the circle fitting function can be tested by slicing stem points height-wise with the Extract section tool and fitting circles to these slices. I believe with your expertise the algorithm logic and speed could be elevated to a new level.

**Comment by truebelief** [comment]
I am troubleshooting the last part of the plugin and will update the code today.

**Comment by truebelief** [comment]
@dgirardeau Thanks again for all the heavy-lifting code cleaning. The tidied code ran smoothly on my PC (Win10). After testing with a more complex dataset, I addressed an index mismatch bug in the final segmentation step. The changes are minor and located in only a few spots. Hopefully, the differences in the rebase way are more noticeable this time around.

**Pull request merged**
